# Concatenation and Splitting of arrays

- Creare una lista es4 di 36 valori interi crescenti partendo da 1

In [71]:
import numpy as np
es4=np.arange(1,37)
es4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

- punto 2: Trasformarlo in un array di dimensione 6x6

In [72]:
es4=es4.reshape(6,6)
es4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- punto 3:Estrarre tre subarray di dimensione 2x2 dalle prime due colonne (sub1,
sub2, sub3)

In [73]:
#prima isolo le prime due colonne
es4_b=es4[:,:2].copy()
es4_b

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [93]:
sub1,sub2,sub3= np.vsplit(es4_b,[2,4])

print("sub1:\n",sub1)
print("sub2:\n",sub2)
print("sub3:\n",sub3)

sub1:
 [[1 2]
 [7 8]]
sub2:
 [[13 14]
 [19 20]]
sub3:
 [[25 26]
 [31 32]]


- punto 4: concatenarli, prima usando axis=0, poi axis=1

In [75]:
np.concatenate([sub1,sub2,sub3])

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [76]:
np.concatenate([sub1,sub2,sub3],axis=1)

array([[ 1,  2, 13, 14, 25, 26],
       [ 7,  8, 19, 20, 31, 32]])

- punto 5: Da es4 estrarre un subarray formato dalle prime due righe (sub4)

In [79]:
sub4=es4[:2,:]
sub4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

- punto 6: concatenate sub1 e sub4

In [80]:
np.hstack([sub1,sub4])

array([[ 1,  2,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  7,  8,  9, 10, 11, 12]])

- punto 7: Trasformate sub4 da 2x6 a 6x2 (le 2 righe diventano 2 colonne)

In [96]:
sub4=sub4.reshape(6,2)
print("sub4 trasformato: \n", sub4)

sub4 trasformato: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


- punto8: Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2 (sub5)

In [94]:
sub5=np.concatenate([sub1,sub2,sub3])
print("sub5: \n", sub5)

sub5: 
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]


- punto 9: concatenare sub4 trasformato con sub 5

In [90]:
np.vstack([sub4,sub5])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])