# subarrays as copies or views

- Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con
valore massimo (incluso) uguale a 20

In [76]:
import numpy as np
es3= np.random.randint(21, size=(3,3))
es3

array([[13, 16, 15],
       [ 6,  3,  4],
       [20,  4,  8]])

In [77]:
#estrarre il subarray formato dalla seconda riga (es3-sub) come vista e visualizzarlo
es3_sub=es3[1,:]
es3_sub

array([6, 3, 4])

In [83]:
print("valori della colonna prima della moltiplicazione:",es3[:,1])

#moltiplicare per 3 tutti gli elementi della seconda colonna
es3[:,1]=es3[:,1]*3

print("valori colonna dopo moltiplicazione:",es3[:,1])


valori della colonna prima della moltiplicazione: [16  3  4]
valori colonna dopo moltiplicazione: [48  9 12]


In [84]:
#visualizzare es3sub, è cambiato rispeto a prima?
es3_sub

array([6, 9, 4])

sì, è cambiato in quanto il subarray era una 'views' e non una copia

In [85]:
es3_sub_Copy=es3[:,2].copy()
es3_sub_Copy

array([15,  4,  8])

In [86]:
#sommare 10 a tutti gli elementi di es3subCopy
es3_sub_Copy+10

array([25, 14, 18])

In [87]:
#visualizzare es3, contiene la modifica del punto 6?
es3

array([[13, 48, 15],
       [ 6,  9,  4],
       [20, 12,  8]])

no, non è cambiato es3 poichè la modifica è stata apportata su una copia e non sull'aray originale

In [88]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [89]:
x.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [92]:
x[np.newaxis,:2]

array([[1, 2]])

In [94]:
x[np.newaxis,2:]

array([[3, 4]])