# esercizio **array slicing: One dimensional**

creare array di 10 valori che parta da 5 e vada fino a 15

In [12]:
import numpy as np
x=np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#primi sei valori
x[:6]

array([ 5,  6,  7,  8,  9, 10])

In [14]:
#elementi dopo l'indice 3
x[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [15]:
#elementi dopo il terzo elemento
x[2:]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#subarray con valori 8,9,10,11,12
x[3:8]

array([ 8,  9, 10, 11, 12])

In [17]:
#un elemento ogni 3 artendo dal primo
x[::3]

array([ 5,  8, 11, 14])

In [18]:
#un elemento ogni 3 partendo dal terzo elemento
x[3::3]

array([ 8, 11, 14])

# esercizio array slicing: Multi dimensional

- Creare un array *es2a* di valori casuali interi (randint) di dimensione 4x6, con
valore massimo (incluso) uguale a 15.

In [23]:
import numpy as np
es2a= np.random.randint(16, size=(4,6))
es2a

array([[ 7, 10,  2,  6, 13, 11],
       [14, 13,  6,  0,  5,  4],
       [ 8, 12,  1,  1,  1,  6],
       [ 5, 15,  6, 10,  3, 15]])

In [24]:
#prime tre righe, prime tre colonne
es2a[:3,:3]

array([[ 7, 10,  2],
       [14, 13,  6],
       [ 8, 12,  1]])

In [25]:
#seconda e terza riga, quarta, quinta e sesta colonna
es2a[1:3,3:]

array([[0, 5, 4],
       [1, 1, 6]])

In [26]:
#elementi dopo il terzo elemento
es2a[3:,3:]

array([[10,  3, 15]])

In [32]:
#invertire l’ordine delle sole righe;
#invertire l’ordine delle sole colonne

es2a[::-1,::], es2a[::,::-1]

(array([[ 5, 15,  6, 10,  3, 15],
        [ 8, 12,  1,  1,  1,  6],
        [14, 13,  6,  0,  5,  4],
        [ 7, 10,  2,  6, 13, 11]]),
 array([[11, 13,  6,  2, 10,  7],
        [ 4,  5,  0,  6, 13, 14],
        [ 6,  1,  1,  1, 12,  8],
        [15,  3, 10,  6, 15,  5]]))

- Creare un array *es2b* di valori casuali interi (randint) di dimensione 2x5x5,
con valore massimo (incluso) uguale a 30.

In [36]:
es2b= np.random.randint(31, size=(2,5,5))
es2b

array([[[ 9, 27, 20, 28,  1],
        [14, 18, 24, 27, 24],
        [17,  3,  2,  4, 27],
        [23,  4, 17,  3, 13],
        [29, 25, 16, 19,  1]],

       [[ 8,  2, 11, 12, 24],
        [ 9, 15, 13,  5, 10],
        [15, 26,  8, 14, 28],
        [ 2, 25, 18, 22, 16],
        [25, 25, 21,  5, 25]]])

In [39]:
#selezionare il primo subarray, da quello le prime due righe e le colonne dalla seconda alla quarta
es2b[0,:2,1:4]

array([[27, 20, 28],
       [18, 24, 27]])

In [51]:
#selezionare da entrambi i subarray le prime due righe e prime due colonne e invertire righe e colonne
point=es2b[:2,:2:,:2]
point

array([[[ 9, 27],
        [14, 18]],

       [[ 8,  2],
        [ 9, 15]]])

In [52]:
point[::-1,::-1]

array([[[ 9, 15],
        [ 8,  2]],

       [[14, 18],
        [ 9, 27]]])