**esercizio**

In [2]:
import numpy as np

In [8]:
#creare lista di 50 elemetni con np.zeros()
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(50, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [10]:
#creare matrice 2x5 di numeri interi
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
#creare matrice 3x3 con valori 12.34 usando funzione np.full()
np.full((3,3),12.34)

array([[12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34]])

In [26]:
#creare lista di 10 elementi, che inizia da 6 e incrementa di 4
np.arange(6,46,4)

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42])

In [29]:
#creare lista di elementi tra 0 e 100 distanziati di 5
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [30]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [32]:
#creare lista 1x10 di valori casuali compresi tra 0 e 1
np.random.random((1,10))

array([[0.03712479, 0.2793309 , 0.74555756, 0.94935232, 0.93406244,
        0.12507414, 0.52125562, 0.71115979, 0.73900638, 0.22331711]])

In [33]:
#creare matrice 2x10 di valori con distribuzione
#gaussiana con media 0 e deviazione standard 1
np.random.normal(0,1,(2,10))

array([[-0.32974808, -0.31238389, -0.32226825,  2.60174037,  0.10212443,
         0.13919302,  0.0979725 ,  0.69866782,  0.40583105, -0.76566902],
       [ 1.00344209,  1.09354503,  1.09238928,  0.71821744, -1.02507134,
         0.27105609,  0.08655185, -0.36032052,  0.29800603,  0.44911694]])