- **esercizio array's attributes**

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

Each array has attributes **ndim** (the number of dimensions), **shape** (the size of each dimension), and **size** (the total size of the array):

- **attributes of x3**

In [5]:
print("x3 ndim:",x3.ndim)

x3 ndim: 3


In [6]:
print("x3 shape,o forma:",x3.shape)

x3 shape,o forma: (3, 4, 5)


In [7]:
print("x3 total size:",x3.size)

x3 total size: 60


- **attributes of x1**

In [8]:
print("x1 ndim,the number of dimension:",x1.ndim)

x1 ndim,the number of dimension: 1


In [11]:
print("x1 shape, forma di ogni blocco:",x1.shape)

x1 shape, forma di ogni blocco: (6,)


In [12]:
print("x1 size, forma della matrice in generale:",x1.size)

x1 size, forma della matrice in generale: 6


- **attributes of x2**

In [14]:
print("x2 ndim, quante dimensioni:",x2.ndim)
print("x2 shape, forma di ogni blocco:",x2.shape)
print("x2 size, ovvero forma di tutta la matrice:",x2.size)

x2 ndim, quante dimensioni: 2
x2 shape, forma di ogni blocco: (3, 4)
x2 size, ovvero forma di tutta la matrice: 12


- **ESERCIZIO LEZIONE 1/10**

- visualizzare ndim, shape e saze degli aray x2 e x3
- modificare x1 in modo che ndim=2 e shape=4,5

In [15]:
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x1b= np.random.randint(10,size=(4,5))
x1b

array([[3, 2, 3, 4, 1],
       [2, 9, 1, 4, 6],
       [8, 2, 3, 0, 0],
       [6, 0, 6, 3, 3]])

In [18]:
print("x1b ndim:",x1b.ndim)
print("x1b shape:", x1b.shape)

x1b ndim: 2
x1b shape: (4, 5)


In [20]:
# Cosa indica il primo parametro di random.randint posto al valore 10?
x1b= np.random.randint(10,size=(4,5))
# indica che i valori saranno compresi tra 0 incluso e 10 escluso.

- **ESERCIZIO N. 2 , LEZIONE 1/10**

In [22]:
import numpy as np
np.random.seed(0)

In [24]:
#Creare un array es1 di valori casuali interi (randint) di dimensione 3x5, con valore massimo (incluso) uguale a 8.
#Visualizzare es1
es1= np.random.randint(9,size=(3,5))
es1

array([[7, 7, 8, 1, 5],
       [8, 4, 3, 0, 3],
       [5, 0, 2, 3, 8]])

In [25]:
#Selezionare gli elementi che hanno valore 5 
#prima utilizzando la posizione come indice,
#poi usando la forma negativa dalla fine dell’array
es1[0,4]

5

In [26]:
es1[2,0]

5

In [27]:
es1[0,-1]

5

In [30]:
es1[2,-5]

5

In [37]:
#Selezionare il primo elemento della seconda riga, 
#il quinto elemento della prima riga,
#il secondo elemento della seconda colonna,
#il quarto elemento della terza colonna

es1[1,0] , es1[0,4], es1[1,1]
#non esiste il quarto elemento della terza colonna


(8, 5, 4)

In [38]:
#Sommare 10 all’elemento es1[0,0], 
#sottrarre 5 all’elemento es1[2,3],
#sommare l’elemento es1[0,0] all’elemento es1[1,0] e il risultato metterlo in es1[2,0] 
#(non usare i valori, usare i riferimenti alle posizioni dell’array

es1[0,0]+10

17

In [48]:
es1[2,3]-5

-2

In [50]:
a=es1[0,0]+es1[1,0]
a

15

In [51]:
es1[2,0]=a
es1

array([[ 7,  7,  8,  1,  5],
       [ 8,  4,  3,  0,  3],
       [15,  0,  2,  3,  8]])